# Generated by Django 4.1.2 on 2022-10-21 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guildName', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=100)),
                ('numMembers', models.IntegerField()),
                ('status', models.IntegerField(blank=True)),
                ('required', models.IntegerField(blank=True)),
                ('gp', models.IntegerField()),
                ('bannerColor', models.CharField(blank=True, max_length=25)),
                ('bannerLogo', models.CharField(blank=True, max_length=25)),
                ('message', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
