# Generated by Django 4.1.2 on 2022-10-21 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Striker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guild',
            name='required',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='guild',
            name='status',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerName', models.CharField(max_length=30)),
                ('playerId', models.CharField(max_length=15)),
                ('allycode', models.IntegerField()),
                ('level', models.IntegerField()),
                ('gp', models.IntegerField()),
                ('gpChar', models.IntegerField()),
                ('gpShip', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('guildMemberLevel', models.IntegerField()),
                ('guildRefId', models.CharField(max_length=30)),
                ('GrandArenaLifeTime', models.IntegerField()),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Striker.guild')),
            ],
        ),
    ]
