# Generated by Django 4.1.2 on 2022-10-22 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Striker', '0002_alter_guild_required_alter_guild_status_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strike_date', models.DateField()),
                ('ishard', models.BooleanField(default=True)),
                ('comments', models.TextField(blank=True, max_length=200)),
                ('activity', models.CharField(choices=[('TW', 'TW'), ('TB', 'TB'), ('Tickets', 'Tickets'), ('Other', 'Other')], max_length=10)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Striker.player')),
            ],
        ),
    ]
