# Generated by Django 4.1.2 on 2022-10-23 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Striker', '0003_strike'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='strike',
            options={'ordering': ['-strike_date']},
        ),
        migrations.AlterField(
            model_name='player',
            name='guild',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Striker.guild'),
        ),
    ]
