# Generated by Django 4.1.2 on 2022-10-23 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Striker', '0004_alter_strike_options_alter_player_guild'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='GrandArenaLifeTime',
        ),
        migrations.RemoveField(
            model_name='player',
            name='guildRefId',
        ),
    ]
