# Generated by Django 4.1.2 on 2022-10-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Striker', '0005_remove_player_grandarenalifetime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guild',
            old_name='numMembers',
            new_name='members',
        ),
        migrations.RemoveField(
            model_name='guild',
            name='description',
        ),
        migrations.RemoveField(
            model_name='guild',
            name='guildName',
        ),
        migrations.AddField(
            model_name='guild',
            name='desc',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='guild',
            name='guildId',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='guild',
            name='name',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
