# Generated by Django 4.1.2 on 2022-10-28 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Striker', '0006_rename_nummembers_guild_members_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='playerName',
            new_name='name',
        ),
        migrations.AddField(
            model_name='player',
            name='updated',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.CreateModel(
            name='Toon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toonID', models.CharField(max_length=45)),
                ('toonName', models.CharField(max_length=45)),
                ('nameKey', models.CharField(max_length=45)),
                ('rarity', models.IntegerField()),
                ('toonLevel', models.IntegerField()),
                ('gp', models.IntegerField()),
                ('gearLevel', models.IntegerField()),
                ('primaryUnitStat', models.IntegerField()),
                ('relic', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Striker.player')),
            ],
        ),
    ]
