# Generated by Django 3.2 on 2022-11-08 20:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Striker', '0007_rename_playername_player_name_player_updated_toon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strike',
            name='strike_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
