# Generated by Django 4.1.2 on 2022-11-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Striker', '0009_alter_strike_strike_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['playerId']},
        ),
        migrations.AddField(
            model_name='toon',
            name='combatType',
            field=models.IntegerField(default=1),
        ),
    ]
