# Generated by Django 4.1.2 on 2022-11-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Striker', '0010_alter_player_options_toon_combattype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toon',
            name='combatType',
            field=models.IntegerField(blank=True),
        ),
    ]
