# Generated by Django 4.1.2 on 2022-11-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Striker', '0011_alter_toon_combattype'),
    ]

    operations = [
        migrations.AddField(
            model_name='toon',
            name='isZeta',
            field=models.BooleanField(default=False),
        ),
    ]
