# Generated by Django 4.1.2 on 2022-11-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Striker', '0011_alter_toon_combattype'),
    ]

    operations = [
        migrations.AddField(
            model_name='toon',
            name='forceAlignment',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='toon',
            name='isZeta',
            field=models.IntegerField(default=1),
        ),
    ]
