# Generated by Django 4.1.2 on 2022-11-18 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Striker', '0012_toon_forcealignment_toon_iszeta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toon',
            name='forceAlignment',
        ),
        migrations.RemoveField(
            model_name='toon',
            name='isZeta',
        ),
    ]
