# Generated by Django 4.1.2 on 2022-11-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Striker', '0013_remove_toon_forcealignment_remove_toon_iszeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='toon',
            name='crew',
            field=models.CharField(default=1, max_length=45),
        ),
    ]
