# Generated by Django 4.1.2 on 2022-11-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Striker', '0014_toon_crew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toon',
            name='crew',
            field=models.CharField(blank=True, max_length=45),
        ),
    ]
