# Generated by Django 4.1.2 on 2022-11-23 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Striker', '0015_alter_toon_crew'),
    ]

    operations = [
        migrations.AddField(
            model_name='toon',
            name='isZeta',
            field=models.BooleanField(default=True),
        ),
    ]
