# Generated by Django 4.1.2 on 2022-11-23 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Striker', '0016_toon_iszeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toon',
            name='isZeta',
            field=models.CharField(blank=True, max_length=45),
        ),
    ]
