# Generated by Django 4.1.2 on 2022-11-24 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Striker', '0018_toon_forcealignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toon',
            name='forceAlignment',
            field=models.CharField(blank=True, max_length=45),
        ),
    ]
