# Generated by Django 4.1.2 on 2022-11-25 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Striker', '0020_toon_crew1_toon_crew2_toon_crew3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toon',
            old_name='crew1',
            new_name='crewone',
        ),
        migrations.RenameField(
            model_name='toon',
            old_name='crew2',
            new_name='crewthree',
        ),
        migrations.RenameField(
            model_name='toon',
            old_name='crew3',
            new_name='crewtwo',
        ),
    ]
