# Generated by Django 4.1.2 on 2022-11-25 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Striker', '0021_rename_crew1_toon_crewone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toon',
            name='crewone',
        ),
        migrations.RemoveField(
            model_name='toon',
            name='crewthree',
        ),
        migrations.RemoveField(
            model_name='toon',
            name='crewtwo',
        ),
    ]
