# Generated by Django 3.2 on 2022-11-26 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Striker', '0023_mod_modstat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillId', models.CharField(max_length=30)),
                ('tier', models.SmallIntegerField()),
                ('nameKey', models.CharField(max_length=30)),
                ('isZeta', models.BooleanField(default=False)),
                ('tiers', models.SmallIntegerField()),
                ('toon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Striker.toon')),
            ],
        ),
        migrations.CreateModel(
            name='Equipped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipmentId', models.CharField(blank=True, max_length=6)),
                ('slot', models.SmallIntegerField(blank=True)),
                ('nameKey', models.CharField(blank=True, max_length=35)),
                ('toon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Striker.toon')),
            ],
        ),
    ]
