# Generated by Django 3.2 on 2022-11-26 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Striker', '0024_equipped_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipCrew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitId', models.CharField(blank=True, max_length=40)),
                ('skillId', models.CharField(blank=True, max_length=40)),
                ('skillessCrewAbilityId', models.CharField(blank=True, max_length=35)),
                ('slot', models.SmallIntegerField(blank=True)),
                ('requiredTier', models.SmallIntegerField(blank=True)),
                ('requiredRarity', models.SmallIntegerField(blank=True)),
                ('requiredRelicTier', models.SmallIntegerField(blank=True)),
                ('gp', models.SmallIntegerField(blank=True)),
                ('cp', models.DecimalField(decimal_places=5, max_digits=10)),
                ('toon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Striker.toon')),
            ],
        ),
    ]
