# Generated by Django 3.2 on 2022-11-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Striker', '0025_shipcrew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='guildMemberLevel',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
