# Generated by Django 3.2 on 2022-11-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Striker', '0026_alter_player_guildmemberlevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='toon',
            name='xp',
            field=models.IntegerField(default=0),
        ),
    ]
