# Generated by Django 3.2 on 2022-11-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Striker', '0027_toon_xp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toon',
            name='combatType',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
