# Generated by Django 3.2 on 2022-10-20 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guildName', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=100)),
                ('numMembers', models.IntegerField()),
                ('status', models.IntegerField()),
                ('required', models.IntegerField()),
                ('gp', models.IntegerField()),
                ('bannerColor', models.CharField(max_length=25)),
                ('bannerLogo', models.CharField(max_length=25)),
                ('message', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modId', models.CharField(max_length=15)),
                ('modLevel', models.IntegerField()),
                ('tier', models.IntegerField()),
                ('slot', models.IntegerField()),
                ('set', models.IntegerField()),
                ('pips', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerName', models.CharField(max_length=30)),
                ('playerId', models.CharField(max_length=15)),
                ('allycode', models.IntegerField()),
                ('level', models.IntegerField()),
                ('gp', models.IntegerField()),
                ('gpChar', models.IntegerField()),
                ('gpShip', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('guildMemberLevel', models.IntegerField()),
                ('guildRefId', models.CharField(max_length=30)),
                ('GrandArenaLifeTime', models.IntegerField()),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StrikerGMT.guild')),
            ],
        ),
        migrations.CreateModel(
            name='Toon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toonID', models.CharField(max_length=30)),
                ('toonName', models.CharField(max_length=30)),
                ('nameKey', models.CharField(max_length=45)),
                ('rarity', models.IntegerField()),
                ('toonLevel', models.IntegerField()),
                ('gp', models.IntegerField()),
                ('xp', models.IntegerField()),
                ('gearLevel', models.IntegerField()),
                ('primaryUnitStat', models.IntegerField()),
                ('relic', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StrikerGMT.player')),
            ],
        ),
        migrations.CreateModel(
            name='Strike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strike_date', models.DateField()),
                ('ishard', models.BooleanField(default=True)),
                ('comments', models.TextField(blank=True, max_length=200)),
                ('activity', models.CharField(choices=[('TW', 'TW'), ('TB', 'TB'), ('Tickets', 'Tickets'), ('Other', 'Other')], max_length=10)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StrikerGMT.player')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillId', models.CharField(max_length=15)),
                ('tier', models.IntegerField()),
                ('nameKey', models.CharField(max_length=15)),
                ('isZeta', models.BooleanField(default=False)),
                ('tiers', models.IntegerField()),
                ('toon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StrikerGMT.toon')),
            ],
        ),
        migrations.CreateModel(
            name='Mod_Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modID', models.CharField(max_length=15)),
                ('unitStat', models.IntegerField()),
                ('value', models.IntegerField()),
                ('roll', models.IntegerField()),
                ('statType', models.CharField(max_length=15)),
                ('mod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StrikerGMT.mod')),
            ],
        ),
        migrations.AddField(
            model_name='mod',
            name='toon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StrikerGMT.toon'),
        ),
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gearId', models.CharField(max_length=15)),
                ('slot', models.IntegerField()),
                ('nameKey', models.CharField(max_length=15)),
                ('toon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StrikerGMT.toon')),
            ],
        ),
    ]
